const teams = [
  {
    name: "Emanuele",
    surname: "Vutera",
    age: 27,
    city: "Perugia",
    hobby: "Videogames",
    favoriteFood: "Pasta con il ragù",
    favoriteVideoGame: "League of Legends",
    favoriteFilm: "Cambia la tua vita con un click",
    favoriteBook: "",
    petName: "",
  },

  {
    name: "Luca",
    surname: "Potenza",
    age: 29,
    city: "Roma",
    hobby: "Gaming",
    favoriteFood: "Pizza",
    favoriteVideoGame: "Red Redemption 2",
    favoriteFilm: "Old Henry",
    favoriteBook: "Tex",
    petName: "Totò & Sammy",
  },
  {
    name: "Gioele",
    surname: "Brunori",
    age: 24,
    city: "Cingoli",
    hobby: "kick box",
    favoriteFood: "pasta",
    favoriteVideoGame: "dark souls 3",
    favoriteFilm: "roadhouse",
    favoriteBook: "la casa",
    petName: "Randal",
  },
];
